coverage:
  status:
    project:
      default:
        target: 80
        paths: ["src"]
    patch:
      default:
        target: 75
        paths: ["src"]

ignore:
  - "setup.py"
  - "integration"
  - "tests"
  - "scripts"
