name: Tests
on:
  push:
    branches:
      - 'main'
      - 'development'
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, ubuntu-latest ]

    steps:
      - uses: actions/checkout@v4.2.2
      - name: Set up Python 3.12.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.6
      # This is needed so MacOS can find the libsodium library installed by Homebrew
      - name: Install dependencies for MacOS
        if: matrix.os == 'macos-latest'
        run: |
          export DYLD_LIBRARY_PATH="/usr/local/lib:/opt/homebrew/lib:$DYLD_LIBRARY_PATH"
          echo "DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH" >> $GITHUB_ENV
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest mockito==1.4.0 pytest-cov codecov
          pip install -r requirements.txt
      - name: Run tests
        run: |
            pytest --cov=./ --cov-report=xml
            codecov
